name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^7.6.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  flutter_bloc: ^8.1.6
  flow_builder: ^0.0.9
  equatable: ^2.0.5

  # Generate
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Utility & Widget
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0  
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  bubble: ^1.2.1

  # Config
  easy_localization: ^3.0.3
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  
  # Modules
  core:
    path: module/core
  gen:
    path: module/gen
  widget:
    path: module/widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
